language: cpp
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost1.48-dev libboost1-regex1.48 libboost-thread1.48 libboost-filesystem1.48 libboost-system1.48
  - wget http://googletest.googlecode.com/files/gtest-1.6.0.zip
  - unzip -q gtest-1.6.0.zip
  - cd gtest-1.6.0
  - cmake . && make
  - cd ..
  - cmake -D CMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DCMAKE_LIBRARY_PATH=gtest-1.6.0 -DCMAKE_INCLUDE_PATH=gtest-1.6.0/include .
script: make
after_script: make test
compiler:
  - clang
  - gcc
env:
  matrix:
    - CMAKE_BUILD_TYPE=DEBUG
    - CMAKE_BUILD_TYPE=RELEASE
notifications:
  email:
    on_success: always
    on_failure: always
