#include "rpg2k/define/define.hxx"

const char* rpg2k::define::LcfMapTree =
"array2d Grobal\n"
"{\n"
"	[1]: string name = \"\";\n"
"	[2]: int parent_map_id;\n"
"\n"
"	[3]: int indentation;\n"
"	[4]: int type;\n"
"	[5]: int unknown0;\n"
"	[6]: int unknown1;\n"
"	[7]: bool isOpen = false; // relate with nest?\n"
"\n"
"	[11]: int music_type;\n"
"	[12]: music music;\n"
"\n"
"	[21]: int backdrop_type;\n"
"	[22]: string backdrop;\n"
"\n"
"	[31]: int teleport;\n"
"	[32]: int escape;\n"
"	[33]: int save;\n"
"\n"
"	[41]: array2d Encount\n"
"	{\n"
"		[1]: int enemyGroup_id;\n"
"	};\n"
"	[44]: int encuntStep = 25;\n"
"\n"
"	[51]: binary areaRange; // uint32t[4] = { startx, starty, endx, endy };\n"
"};\n"
"\n"
"ber_enum mapExist;\n"
"\n"
"array1d StartPoint\n"
"{\n"
"	[1]: int party_map_id;\n"
"	[2]: int partyX = 0;\n"
"	[3]: int partyY = 0;\n"
"\n"
"	[11]: int boat_map_id = 0;\n"
"	[12]: int boatX = 0;\n"
"	[13]: int boatY = 0;\n"
"\n"
"	[21]: int ship_map_id = 0;\n"
"	[22]: int shipX = 0;\n"
"	[23]: int shipY = 0;\n"
"\n"
"	[31]: int airship_map_id = 0;\n"
"	[32]: int airshipX = 0;\n"
"	[33]: int airshipY = 0;\n"
"};\n"
;
