#include "rpg2k/define/define.hxx"

const char* rpg2k::define::LcfMapUnit =
"array1d Grobal\n"
"{\n"
"	[1]: int chip_set_id = 1;\n"
"	[2]: int width     = 20;\n"
"	[3]: int height    = 15;\n"
"\n"
"	[11]: int scroll_type;\n"
"\n"
"	[31]: bool usePanorama = false;\n"
"	[32]: string panorama;\n"
"	[33]: bool scrollPanoramaH = false;\n"
"	[34]: bool scrollPanoramaV = false;\n"
"	[35]: bool autoScrollPanoramaH = false;\n"
"	[36]: int autoScrollPanoramaSpeedH = 0;\n"
"	[37]: bool autoScrollPanoramaV = false;\n"
"	[38]: int autoScrollPanoramaSpeedV = 0;\n"
"\n"
"	[71]: binary lower;\n"
"	[72]: binary upper;\n"
"\n"
"	[81]: array2d event\n"
"	{\n"
"		[1]: string name;\n"
"		[2]: int x = 0;\n"
"		[3]: int y = 0;\n"
"		// [4]:\n"
"		[5]: array2d Page\n"
"		{\n"
"			[2]: array1d Term\n"
"			{\n"
"				[1]: int flag = 0;\n"
"				[2]: int switch_id1 = 1;\n"
"				[3]: int switch_id2 = 1;\n"
"				[4]: int variable_id = 1;\n"
"				[5]: int value = 0;\n"
"				[6]: int item_id = 1;\n"
"				[7]: int char_id = 1;\n"
"				[8]: int timerLeft = 0;\n"
"				[9]: int timerLeft2 = 0;\n"
"				[10]: int compare_type = 0;\n"
"			};\n"
"\n"
"			[21]: string char_set;\n"
"			[22]: int char_set_pos = 0;\n"
"			[23]: int char_setdir = 2;\n"
"			[24]: int char_setPat = 1;\n"
"			[25]: bool semiTrans = false;\n"
"\n"
"			[31]: int action = 0;\n"
"			[32]: int freq = 3;\n"
"			[33]: int start_type = 0;\n"
"			[34]: int priority_type = 0;\n"
"			[35]: bool noPile = false;\n"
"			[36]: int anime_type = 0;\n"
"			[37]: int speed = 3;\n"
"\n"
"			[41]: array1d move\n"
"			{\n"
"				[11]: int length = 0;\n"
"				[12]: binary data;\n"
"\n"
"				[21]: bool repeat = true;\n"
"				[22]: bool pass = false;\n"
"			};\n"
"\n"
"			[51]: int eventLength = 0;\n"
"			[52]: event event;\n"
"		};\n"
"	};\n"
"\n"
"	[91]: int saveTime;\n"
"};\n"
;
