namespace rpg2k { namespace define { const char* LcfDataBase =
    "array1d Grobal\n"
    "{\n"
    "   [11]: array2d character\n"
    "   {\n"
    "       [ 1]: string name;\n"
    "       [ 2]: string title;\n"
    "       [ 3]: string char_set;\n"
    "       [ 4]: int char_set_pos = 0;\n"
    "       [ 5]: bool semi_trans = false;\n"
    "\n"
    "       [ 7]: int start_level = 1;\n"
    "       [ 8]: int max_level = 50;\n"
    "       [ 9]: bool critical = true;\n"
    "       [10]: int critical_rate = 30 ;\n"
    "\n"
    "       [15]: string face_set;\n"
    "       [16]: int face_set_pos = 0;\n"
    "\n"
    "       [21]: bool double_hand = false;\n"
    "       [22]: bool equip_fix = false;\n"
    "       [23]: bool ai_action = false;\n"
    "       [24]: bool strong_defence = false;\n"
    "\n"
    "       [31]: binary status; // std::array<std::array<uint16_t, 6>, max_level>\n"
    "\n"
    "       [41]: int exp_basic;\n"
    "       [42]: int exp_increase;\n"
    "       [43]: int exp_correction = 0;\n"
    "\n"
    "       [51]: binary equipment; // std::array<uint16_t, 5>\n"
    "\n"
    "       [56]: int unarmed_attack = 1; // battle anime id\n"
    "       [57]: int job = 0;\n"
    "       [58]: int battle_anime = 0;\n"
    "\n"
    "       [60]: int battle_x = 0;\n"
    "       [61]: int battle_y = 0;\n"
    "       [62]: int attackAnime = 0;\n"
    "       [63]: array2d skill\n"
    "       {\n"
    "           [1]: int level;\n"
    "           [2]: int skill_id = 1;\n"
    "       };\n"
    "       [66]: bool useOriginalCommand = false;\n"
    "       [67]: string originalCommand;\n"
    "\n"
    "       [71]: int condition_data_num = 0;\n"
    "       [72]: binary condition_data;\n"
    "       [73]: int attrib_data_num = 0;\n"
    "       [74]: binary attrib_data;\n"
    "\n"
    "       [80]: binary battle_command; // std::array<uint32_t, 6>\n"
    "   };\n"
    "   [12]: array2d skill\n"
    "   {\n"
    "       [1]: string name;\n"
    "       [2]: string comment;\n"
    "       [3]: string message_l1;\n"
    "       [4]: string message_l2;\n"
    "       [7]: int message_failed;\n"
    "       [8]: int type = 0;\n"
    "\n"
    "       [11]: int using_mp_amount = 0;\n"
    "       [12]: int range = 0;\n"
    "       [13]: int switch_id = 1;\n"
    "       [14]: int anime_id = 1;\n"
    "       [16]: sound sound;\n"
    "       [18]: bool use_at_field = true;\n"
    "       [19]: bool use_at_battle = false;\n"
    "       [20]: bool condition_effect = false;\n"
    "       [21]: int blow_relation = 0;\n"
    "       [22]: int mental_relation = 3;\n"
    "       [23]: int effect_variance = 4;\n"
    "       [24]: int basic_effect = 0;\n"
    "       [25]: int succeed_rate = 100;\n"
    "\n"
    "       [31]: bool affect_hp = false;\n"
    "       [32]: bool affect_mp = false;\n"
    "       [33]: bool affect_attack = false;\n"
    "       [34]: bool affect_defence = false;\n"
    "       [35]: bool affect_mental = false;\n"
    "       [36]: bool affect_speed = false;\n"
    "       [37]: bool absorption = false;\n"
    "       [38]: bool ignore_defence = false;\n"
    "\n"
    "       [41]: int condition_data_num = 0;\n"
    "       [42]: binary condition_data; // std::vector<uint8_t> (as bool)\n"
    "       [43]: int attrib_data_num = 0;\n"
    "       [44]: binary attrib_data; // std::vector<uint8_t> (as bool)\n"
    "       [45]: bool change_attrib;\n"
    "   };\n"
    "   [13]: array2d item\n"
    "   {\n"
    "       [1]: string name;\n"
    "       [2]: string comment;\n"
    "       [3]: int type = 0;\n"
    "       [5]: int price = 0;\n"
    "       [6]: int usable_time = 1;\n"
    "\n"
    "       [11]: int attack = 0;\n"
    "       [12]: int defence = 0;\n"
    "       [13]: int mind = 0;\n"
    "       [14]: int speed = 0;\n"
    "\n"
    "       [15]: int hand = 0;\n"
    "       [16]: int using_mp = 0;\n"
    "       [17]: int hit_rate = 0;\n"
    "       [18]: int critical_rate = 0;\n"
    "\n"
    "       [20]: int anime_id = 1;\n"
    "\n"
    "       [21]: bool first_strike = false;\n"
    "       [22]: bool double_attack = false;\n"
    "       [23]: bool attack_all = false;\n"
    "       [24]: bool ignore_evasion_rate = false;\n"
    "       [25]: bool prevent_critical = false;\n"
    "       [26]: bool increase_evasion_rate = false;\n"
    "       [27]: bool half_using_mp_ = false;\n"
    "       [28]: bool ignore_terrain_damage = false;\n"
    "       [29]: bool fix_equipment = false;\n"
    "\n"
    "       [31]: int effect_range = 0;\n"
    "       [32]: int hp_amount = 0;\n"
    "       [33]: int hp_rate = 0;\n"
    "       [34]: int mp_amount = 0;\n"
    "       [35]: int mp_rate = 0;\n"
    "\n"
    "       [37]: bool only_at_field = false;\n"
    "       [38]: bool only_for_knockouts = false;\n"
    "\n"
    "       [41]: int increase_hp = 0;\n"
    "       [42]: int increase_mp = 0;\n"
    "       [43]: int increase_attack = 0;\n"
    "       [44]: int increase_defence = 0;\n"
    "       [45]: int increase_mind = 0;\n"
    "       [46]: int increase_speed = 0;\n"
    "\n"
    "       [51]: int message_type = 0;\n"
    "       [53]: int skill_id = 1;\n"
    "       [55]: int switch_id = 1;\n"
    "       [57]: bool use_at_field = true ;\n"
    "       // [58]: bool\n"
    "       [59]: bool use_at_battle = false;\n"
    "\n"
    "       [61]: int equip_data_num = 0;\n"
    "       [62]: binary equip_data; // std::vector<uint8_t> (as bool)\n"
    "       [63]: int condition_data_num = 0;\n"
    "       [64]: binary condition_data; // std::vector<uint8_t> (as bool)\n"
    "       [65]: int attrib_data_num = 0;\n"
    "       [66]: binary attrib_data; // std::vector<uint8_t> (as bool)\n"
    "       [67]: int condition_rate = 0;\n"
    "       [68]: bool condition_flip = false;\n"
    "       [69]: int use_anime_id;\n"
    "\n"
    "       [71]: bool use_skill_as_item = false;\n"
    "       [72]: int job_data_num = 0;\n"
    "       [73]: binary job_data;\n"
    "   };\n"
    "   [14]: array2d enemy\n"
    "   {\n"
    "       [1]: string name;\n"
    "       [2]: string monster;\n"
    "       [3]: int hue = 0;\n"
    "       [4]: int hp = 10;\n"
    "       [5]: int mp = 10;\n"
    "       [6]: int attack = 10;\n"
    "       [7]: int defence = 10;\n"
    "       [8]: int mind = 10;\n"
    "       [9]: int speed = 10;\n"
    "       [10]: bool semi_trans = false;\n"
    "       [11]: int exp = 0;\n"
    "       [12]: int money = 0;\n"
    "       [13]: int dropping_item_id = 0;\n"
    "       [14]: int item_drop_rate = 100;\n"
    "\n"
    "       [21]: bool critical = false;\n"
    "       [22]: int critical_rate = 30;\n"
    "\n"
    "       [26]: bool increase_miss = false;\n"
    "       [28]: bool in_the_air = false;\n"
    "\n"
    "       [31]: int condition_data_num = 0;\n"
    "       [32]: binary condition_data;\n"
    "       [33]: int attrib_data_num = 0;\n"
    "       [34]: binary attrib_data;\n"
    "\n"
    "       [42]: array2d action_pattern\n"
    "       {\n"
    "           [1]: int action_type;\n"
    "           [2]: int basic_action = 1;\n"
    "           [3]: int skill_id = 1;\n"
    "           [4]: int enemy_id = 1;\n"
    "           [5]: int action_term = 0;\n"
    "           [6]: int a = 0;\n"
    "           [7]: int b = 0;\n"
    "           [8]: int switch_id = 1;\n"
    "           [9]: bool on_after_action = false;\n"
    "           [10]: int on_switch_id = 1;\n"
    "           [11]: bool off_after_action = false;\n"
    "           [12]: int off_switch_id = 1;\n"
    "           [13]: int priority = 50;\n"
    "       };\n"
    "   };\n"
    "   [15]: array2d enemy_group\n"
    "   {\n"
    "       [1]: string name;\n"
    "       [2]: array2d enemy_enum\n"
    "       {\n"
    "           [1]: int enemy_id = 1;\n"
    "           [2]: int x = 0;\n"
    "           [3]: int y = 0;\n"
    "           [4]: bool invisible = false;\n"
    "       };\n"
    "       [4]: int terrain_data_num;\n"
    "       [5]: binary terrain_data;\n"
    "\n"
    "       [11]: array2d battle_event\n"
    "       {\n"
    "           [2]: array1d term\n"
    "           {\n"
    "               [1]: int flag = 0;\n"
    "/*\n"
    "                   [bit]\n"
    "                   [0]: switch_1\n"
    "                   [1]: switch_2\n"
    "                   [2]: variable\n"
    "                   [3]: turn\n"
    "                   [4]: consume\n"
    "                   [5]: enemy_state\n"
    "                   [6]: char_state\n"
    "*/\n"
    "               [2]: int switch_id_1 = 1;\n"
    "\n"
    "               [3]: int switch_id_2 = 1;\n"
    "\n"
    "               [4]: int variable_id = 1;\n"
    "               [5]: int value = 0;\n"
    "\n"
    "               [6]: int trun_freq = 0;\n"
    "               [7]: int turn_offset = 0;\n"
    "\n"
    "               [ 8]: int consume_from = 0;\n"
    "               [ 9]: int consume_to = 100;\n"
    "\n"
    "               [10]: int enemy_id = 0;\n"
    "               [11]: int enemy_hp_from = 0;\n"
    "               [12]: int enemy_hp_to = 100;\n"
    "\n"
    "               [13]: int char_id = 1;\n"
    "               [14]: int char_hp_from = 0;\n"
    "               [15]: int char_hp_to = 100;\n"
    "           };\n"
    "\n"
    "           [11]: int event_length = 0;\n"
    "           [12]: event event;\n"
    "       };\n"
    "   };\n"
    "   [16]: array2d terrain\n"
    "   {\n"
    "       [1]: string name;\n"
    "       [2]: int damage = 0;\n"
    "       [3]: int rate = 100;\n"
    "       [4]: string backdrop ;\n"
    "       [5]: bool boat = false;\n"
    "       [6]: bool ship = false;\n"
    "       [7]: bool airship = true;\n"
    "       [9]: bool airship_land = true;\n"
    "\n"
    "       [11]: int char_view_type = 0;\n"
    "\n"
    "       [15]: sound footstep;\n"
    "       [16]: bool on_damage_se;\n"
    "       [17]: int background_type;\n"
    "\n"
    "       [21]: string background_a_name;\n"
    "       [22]: bool background_a_scrollh;\n"
    "       [23]: bool background_a_scrollv;\n"
    "       [24]: int background_a_scrollh_speed;\n"
    "       [25]: int background_a_scrollv_speed;\n"
    "\n"
    "       [30]: bool background_b;\n"
    "       [31]: string background_b_name;\n"
    "       [32]: bool background_b_scrollh;\n"
    "       [33]: bool background_b_scrollv;\n"
    "       [34]: int background_b_scrollh_speed;\n"
    "       [35]: int background_b_scrollv_speed;\n"
    "\n"
    "       [40]: int special_flags;\n"
    "       [41]: int special_back_party;\n"
    "       [42]: int special_back_enemies;\n"
    "       [43]: int special_lateral_party;\n"
    "       [44]: int special_lateral_enemies;\n"
    "       [45]: int grid_location;\n"
    "       [46]: int grid_a;\n"
    "       [47]: int grid_b;\n"
    "       [48]: int grid_c;\n"
    "   };\n"
    "   [17]: array2d attribute\n"
    "   {\n"
    "       [1]: string name;\n"
    "       [2]: int type = 0;\n"
    "\n"
    "       [11]: int rate_a = 300;\n"
    "       [12]: int rate_b = 200;\n"
    "       [13]: int rate_c = 100;\n"
    "       [14]: int rate_d = 50;\n"
    "       [15]: int rate_e = 0;\n"
    "   };\n"
    "   [18]: array2d condition\n"
    "   {\n"
    "       [1]: string name ;\n"
    "       [2]: int type = 0;\n"
    "       [3]: int color = 6;\n"
    "       [4]: int priority = 50;\n"
    "       [5]: int restrict = 0;\n"
    "\n"
    "       [11]: int rate_a = 100;\n"
    "       [12]: int rate_b = 80;\n"
    "       [13]: int rate_c = 60;\n"
    "       [14]: int rate_d = 30;\n"
    "       [15]: int rate_e = 0;\n"
    "\n"
    "       [21]: int cure_turn = 0;\n"
    "       [22]: int cure_rate = 0;\n"
    "       [23]: int shock_cure_rate = 0;\n"
    "\n"
    "       [31]: bool attack = false;\n"
    "       [32]: bool defence = false;\n"
    "       [33]: bool mind = false;\n"
    "       [34]: bool speed = false;\n"
    "       [35]: int hit_rate = 100;\n"
    "\n"
    "       [41]: bool disable_blow_skill = false;\n"
    "       [42]: int blow_relation = 0;\n"
    "       [43]: bool disable_mind_skill = false;\n"
    "       [44]: int mind_relation = 0;\n"
    "\n"
    "       [51]: string message_member;\n"
    "       [52]: string message_enemy;\n"
    "       [53]: string message_already;\n"
    "       [54]: string message_last;\n"
    "       [55]: string message_cure;\n"
    "\n"
    "       [61]: int turn_hp_amount = 0;\n"
    "       [62]: int turn_hp_rate = 0;\n"
    "       [63]: int field_hp_step = 0;\n"
    "       [64]: int field_hp_amount = 0;\n"
    "       [65]: int turn_mp_amount = 0;\n"
    "       [66]: int turn_mp_rate = 0;\n"
    "       [67]: int field_mp_step = 0;\n"
    "       [68]: int field_mp_amount = 0;\n"
    "   };\n"
    "   [19]: array2d battle_anime\n"
    "   {\n"
    "       [1]: string name;\n"
    "       [2]: string battle;\n"
    "       [6]: array2d Effect\n"
    "       {\n"
    "           [1]: int frame_id = 0;\n"
    "           [2]: sound sound;\n"
    "           [3]: int range = 0;\n"
    "           [4]: int red = 31;\n"
    "           [5]: int green = 31;\n"
    "           [6]: int blue = 31;\n"
    "           [7]: int flash = 31;\n"
    "       };\n"
    "       [9]: int range = 0;\n"
    "       [10]: int y_base = 0;\n"
    "       [11]: int use_grid = 0;\n"
    "       [12]: array2d frame\n"
    "       {\n"
    "           [1]: array2d cell\n"
    "           {\n"
    "               [1]: bool visible = true;\n"
    "               [2]: int battle_pos; // or pattern\n"
    "               [3]: int x = 0;\n"
    "               [4]: int y = 0;\n"
    "               [5]: int zoom = 0;\n"
    "               [6]: int red = 100;\n"
    "               [7]: int green = 100;\n"
    "               [8]: int blue = 100;\n"
    "               [9]: int chroma = 100;\n"
    "               [10]: int transparency = 0;\n"
    "           };\n"
    "       };\n"
    "   };\n"
    "   [20]: array2d chip_set\n"
    "   {\n"
    "       [1]: string name;\n"
    "       [2]: string chip_set;\n"
    "       [3]: binary terrain_id; // std::vector<uint16_t>\n"
    "       [4]: binary lower; // std::vector<uint8_t>\n"
    "       [5]: binary upper; // std::vector<uint8_t>\n"
    "\n"
    "       [11]: int ocean_sequence = 0;\n"
    "       [12]: int ocean_speed = 0;\n"
    "   };\n"
    "   [21]: array1d vocabulary\n"
    "   {\n"
    "       [1]: string battle_start;\n"
    "       [2]: string first_strike;\n"
    "       [3]: string escape_success;\n"
    "       [4]: string escape_failure;\n"
    "       [5]: string battle_won;\n"
    "       [6]: string battle_lost;\n"
    "       [7]: string gain_exp;\n"
    "       [8]: string earn_money_begin;\n"
    "       [9]: string earn_money_end;\n"
    "       [10]: string item_get;\n"
    "       [11]: string normalAttack;\n"
    "       [12]: string criticalAttackParty;\n"
    "       [13]: string criticalAttackEnemy;\n"
    "       [14]: string defended;\n"
    "       [15]: string do_nothing;\n"
    "       [16]: string charge_power;\n"
    "       [17]: string self_destruct;\n"
    "       [18]: string run_away;\n"
    "       [19]: string transform;\n"
    "       [20]: string damage_to_enemy;\n"
    "       [21]: string no_damage_to_enemy;\n"
    "       [22]: string damage_to_party;\n"
    "       [23]: string no_damage_to_party;\n"
    "       [24]: string skill_failure_a;\n"
    "       [25]: string skill_failure_b;\n"
    "       [26]: string skill_failure_c;\n"
    "       [27]: string physical_atrack_failure;\n"
    "       [28]: string item_use;\n"
    "       [29]: string parameterRecovery;\n"
    "       [30]: string parameer_up;\n"
    "       [31]: string parameerDown;\n"
    "       [32]: string partyAbusorbParameter;\n"
    "       [33]: string enemyAbusorbParameter;\n"
    "       [34]: string attributeGaurd_up;\n"
    "       [35]: string attributeGaurdDown;\n"
    "       [36]: string level_up;\n"
    "       [37]: string skillMastered;\n"
    "\n"
    "       [41]: string select_action; // shop A\n"
    "       [42]: string select_action_second;\n"
    "       [43]: string buy;\n"
    "       [44]: string sell;\n"
    "       [45]: string cancel;\n"
    "       [46]: string select_buying_item;\n"
    "       [47]: string buying_item_num;\n"
    "       [48]: string end_buy;\n"
    "       [49]: string select_selling_item;\n"
    "       [50]: string selling_item_num;\n"
    "       [51]: string end_sell;\n"
    "\n"
    "       [54]: string v54 ; // shop B\n"
    "       [55]: string v55 ;\n"
    "       [56]: string v56 ;\n"
    "       [57]: string v57 ;\n"
    "       [58]: string v58 ;\n"
    "       [59]: string v59 ;\n"
    "       [60]: string v60 ;\n"
    "       [61]: string v61 ;\n"
    "       [62]: string v62 ;\n"
    "       [63]: string v63 ;\n"
    "       [64]: string v64 ;\n"
    "\n"
    "       [67]: string v67 ; // shop C\n"
    "       [68]: string v68 ;\n"
    "       [69]: string v69 ;\n"
    "       [70]: string v70 ;\n"
    "       [71]: string v71 ;\n"
    "       [72]: string v72 ;\n"
    "       [73]: string v73 ;\n"
    "       [74]: string v74 ;\n"
    "       [75]: string v75 ;\n"
    "       [76]: string v76 ;\n"
    "       [77]: string v77 ;\n"
    "\n"
    "       [80]: string mes0; // hotel A\n"
    "       [81]: string mes1;\n"
    "       [82]: string mes2;\n"
    "       [83]: string hotel_yes;\n"
    "       [84]: string hotel_no;\n"
    "       [85]: string v85 ; // hotel B\n"
    "       [86]: string v86 ;\n"
    "       [87]: string v87 ;\n"
    "       [88]: string v88 ;\n"
    "       [89]: string v89 ;\n"
    "\n"
    "       [92]: string item_owned_num;\n"
    "       [93]: string item_equiped_num;\n"
    "\n"
    "       [95]: string money_name;\n"
    "\n"
    "       [101]: string battle;\n"
    "       [102]: string auto_action;\n"
    "       [103]: string escape;\n"
    "       [104]: string attackCommand;\n"
    "       [105]: string defend;\n"
    "       [106]: string use_item;\n"
    "       [107]: string use_skill;\n"
    "       [108]: string equip;\n"
    "\n"
    "       [110]: string save;\n"
    "\n"
    "       [112]: string discardCurrent;\n"
    "\n"
    "       [114]: string newGame;\n"
    "       [115]: string continue;\n"
    "\n"
    "       [117]: string quit;\n"
    "\n"
    "       [123]: string level;\n"
    "       [124]: string hp;\n"
    "       [125]: string mp;\n"
    "       [126]: string normalCondition;\n"
    "       [127]: string expShort;\n"
    "       [128]: string levelShort;\n"
    "       [129]: string hpShort;\n"
    "       [130]: string mpShort;\n"
    "       [131]: string usingMp;\n"
    "       [132]: string attack;\n"
    "       [133]: string defence;\n"
    "       [134]: string mind;\n"
    "       [135]: string speed;\n"
    "       [136]: string weapon;\n"
    "       [137]: string shield;\n"
    "       [138]: string armor;\n"
    "       [139]: string helmet;\n"
    "       [140]: string other;\n"
    "\n"
    "       [146]: string saveSelectMessage;\n"
    "       [147]: string loadSelectMessage;\n"
    "       [148]: string save_dataPrefix;\n"
    "\n"
    "       [151]: string remindDiscarding;\n"
    "       [152]: string yes;\n"
    "       [153]: string no ;\n"
    "   };\n"
    "   [22]: array1d system\n"
    "   {\n"
    "       [10]: int version = 2000;\n"
    "\n"
    "       [11]: string boat;\n"
    "       [12]: string ship;\n"
    "       [13]: string airship;\n"
    "       [14]: int boat_pos;\n"
    "       [15]: int ship_pos;\n"
    "       [16]: int airship_pos;\n"
    "       [17]: string title;\n"
    "       [18]: string game_over;\n"
    "       [19]: string system;\n"
    "       [20]: string system_2;\n"
    "\n"
    "       [21]: int member_num = 0;\n"
    "       [22]: binary member; // std::vector<uint16_t>\n"
    "\n"
    "       [26]: int menuCommandSize;\n"
    "       [27]: binary menuCommand;\n"
    "\n"
    "       [31]: music tite_bgm;\n"
    "       [32]: music battle_bgm;\n"
    "       [33]: music battleEnd_bgm;\n"
    "       [34]: music inn_bgm;\n"
    "       [35]: music boat_bgm;\n"
    "       [36]: music ship_bgm;\n"
    "       [37]: music airship_bgm;\n"
    "       [38]: music gameOver_bgm;\n"
    "\n"
    "       [41]: sound cursormove_se;\n"
    "       [42]: sound enter_se;\n"
    "       [43]: sound cancel_se;\n"
    "       [44]: sound buzzer_se;\n"
    "       [45]: sound battleStart_se;\n"
    "       [46]: sound escape_se;\n"
    "       [47]: sound enemyAttack_se;\n"
    "       [48]: sound enemyDamaged_se;\n"
    "       [49]: sound memberDamaged_se;\n"
    "       [50]: sound evasion_se;\n"
    "       [51]: sound enemyDefeat_se;\n"
    "       [52]: sound use_item_se;\n"
    "\n"
    "       [61]: int moveErace = 0;\n"
    "       [62]: int moveDisplay = 0;\n"
    "       [63]: int battleStartErace = 0;\n"
    "       [64]: int battleStartDisplay = 0;\n"
    "       [65]: int battleEndErace = 0;\n"
    "       [66]: int battleEndDisplay = 0;\n"
    "\n"
    "       [71]: int wallpaper = 0;\n"
    "       [72]: int font = 0;\n"
    "\n"
    "       [81]: int dummy;\n"
    "       [82]: bool dummy;\n"
    "       [83]: int dummy;\n"
    "       [84]: string defBackdrop;\n"
    "       [85]: array2d dummy\n"
    "       {\n"
    "/*\n"
    "           [1]: int dummy;\n"
    "           [2]: int dummy;\n"
    "\n"
    "           [11]: int dummy;\n"
    "           [12]: int dummy;\n"
    "           [13]: int dummy;\n"
    "           [14]: int dummy;\n"
    "           [15]: int dummy;\n"
    "*/\n"
    "       };\n"
    "\n"
    "       [91]: int saveTime;\n"
    "   };\n"
    "   [23]: array2d Switch {\n"
    "       [1]: string name;\n"
    "   };\n"
    "   [24]: array2d Variable {\n"
    "       [1]: string name;\n"
    "   };\n"
    "   [25]: array2d common_event {\n"
    "       [1]: string name;\n"
    "\n"
    "       [11]: int start_type = 5;\n"
    "       [12]: bool needSwitch = false;\n"
    "       [13]: int switch_id = 1;\n"
    "\n"
    "       [21]: int event_length;\n"
    "       [22]: event event;\n"
    "   };\n"
    "   [26]: array2d common_event_2 {\n"
    "       [1]: string name;\n"
    "\n"
    "       [11]: int start_type = 5;\n"
    "       [12]: bool needSwitch = false;\n"
    "       [13]: int switch_id = 1;\n"
    "\n"
    "       [21]: int event_length;\n"
    "       [22]: event event;\n"
    "   };\n"
    "   [27]: array2d common_event_3 {\n"
    "       [1]: string name;\n"
    "\n"
    "       [11]: int start_type = 5;\n"
    "       [12]: bool needSwitch = false;\n"
    "       [13]: int switch_id = 1;\n"
    "\n"
    "       [21]: int event_length;\n"
    "       [22]: event event;\n"
    "   };\n"
    "   [28]: array2d common_event_4 {\n"
    "       [1]: string name;\n"
    "\n"
    "       [11]: int start_type = 5;\n"
    "       [12]: bool needSwitch = false;\n"
    "       [13]: int switch_id = 1;\n"
    "\n"
    "       [21]: int event_length;\n"
    "       [22]: event event;\n"
    "   };\n"
    "   [29]: array2d battle_command {\n"
    "       [1]: string name;\n"
    "       [2]: int type;\n"
    "   };\n"
    "   [30]: array2d class_1 {\n"
    "       [1]: string name;\n"
    "\n"
    "       [21]: bool double_hand = false;\n"
    "       [22]: bool fixed_equipment = false;\n"
    "       [23]: bool forced_ai_action;\n"
    "       [24]: bool strong_defence;\n"
    "\n"
    "       [31]: binary parameter; // std::array<std::array<uint16_t, 6>, max_level>\n"
    "\n"
    "       [41]: int exp_basic;\n"
    "       [42]: int exp_increase;\n"
    "       [43]: int exp_correction = 0;\n"
    "\n"
    "       [51]: binary equipment; // std::array<uint16_t, 5>\n"
    "\n"
    "       [56]: int unarmed_attack = 1; // battle anime id\n"
    "\n"
    "       [62]: int attack_anime = 0;\n"
    "       [63]: array2d skill\n"
    "       {\n"
    "           [1]: int level;\n"
    "           [2]: int skill_id = 1;\n"
    "       };\n"
    "       [66]: bool useOriginalCommand = false;\n"
    "       [67]: string originalCommand;\n"
    "\n"
    "       [71]: int condition_data_num = 0;\n"
    "       [72]: binary condition_data;\n"
    "       [73]: int attrib_data_num = 0;\n"
    "       [74]: binary attrib_data;\n"
    "\n"
    "       [80]: binary battle_command; // std::array<uint32_t, 6>\n"
    "   };\n"
    "   [31]: array2d class_2 {\n"
    "       [1]: string name;\n"
    "\n"
    "       [21]: bool double_hand = false;\n"
    "       [22]: bool fixed_equipment = false;\n"
    "       [23]: bool forced_ai_action;\n"
    "       [24]: bool strong_defence;\n"
    "\n"
    "       [31]: binary parameter; // std::array<std::array<uint16_t, 6>, max_level>\n"
    "\n"
    "       [41]: int exp_basic;\n"
    "       [42]: int exp_increase;\n"
    "       [43]: int exp_correction = 0;\n"
    "\n"
    "       [51]: binary equipment; // std::array<uint16_t, 5>\n"
    "\n"
    "       [56]: int unarmed_attack = 1; // battle anime id\n"
    "\n"
    "       [62]: int attack_anime = 0;\n"
    "       [63]: array2d skill\n"
    "       {\n"
    "           [1]: int level;\n"
    "           [2]: int skill_id = 1;\n"
    "       };\n"
    "       [66]: bool useOriginalCommand = false;\n"
    "       [67]: string originalCommand;\n"
    "\n"
    "       [71]: int condition_data_num = 0;\n"
    "       [72]: binary condition_data;\n"
    "       [73]: int attrib_data_num = 0;\n"
    "       [74]: binary attrib_data;\n"
    "\n"
    "       [80]: binary battle_command; // std::array<uint32_t, 6>\n"
    "   };\n"
    "   [32]: array2d battle_anime2 {\n"
    "       [1]: string name;\n"
    "       [2]: int attack_motion;\n"
    "\n"
    "       [11]: array2d basic {"
    "           [1]: string name;\n"
    "           [2]: string battle;\n"
    "           [3]: int battle_pos;\n"
    "           [4]: bool use_extended_animation;\n"
    "           [5]: int extended_animation_id;\n"
    "       };\n"
    "       [12]: array2d weapon {\n"
    "           [1]: string name;\n"
    "           [2]: string file;\n"
    "           [3]: int index;\n"
    "           [4]: bool use_extended_animation;\n"
    "           [5]: int extended_animation_id;\n"
    "       };\n"
    "   };\n"
    "};\n"
    ;
} }
