namespace rpg2k { namespace define { const char* LcfDataBase =
#line 1
"array1d Grobal\n"
"{\n"
"	[11]: array2d character\n"
"	{\n"
"		[1]: string name;\n"
"		[2]: string title;\n"
"		[3]: string char_set;\n"
"		[4]: int    char_set_pos = 0;\n"
"		[5]: bool semiTrans = false;\n"
"\n"
"		[ 7]: int  start_lv      = 1   ;\n"
"		[ 8]: int  max_lv        = 50  ;\n"
"		[ 9]: bool critical     = true;\n"
"		[10]: int  criticalRate = 30  ;\n"
"\n"
"		[15]: string face_set;\n"
"		[16]: int    face_set_pos = 0;\n"
"\n"
"		[21]: bool doubleHand    = false;\n"
"		[22]: bool equipFix      = false;\n"
"		[23]: bool aiaction      = false;\n"
"		[24]: bool strongDefence = false;\n"
"\n"
"		[31]: binary status; // std::vector< uint16t >[6][max_lv]\n"
"\n"
"		[41]: int expBasic;\n"
"		[42]: int expIncrease;\n"
"		[43]: int expCorrection = 0;\n"
"\n"
"		[51]: binary equipment; // std::array<uint16t, 5>\n"
"\n"
"		[56]: int unarmedAttack = 1; // battle anime id\n"
"		[57]: int job = 0;\n"
"		[58]: int battleAnime = 0;\n"
"\n"
"		[60]: int battleX = 0;\n"
"		[61]: int battleY = 0;\n"
"		[62]: int attackAnime = 0;\n"
"		[63]: array2d skill\n"
"		{\n"
"			[1]: int level;\n"
"			[2]: int skill_id = 1;\n"
"		};\n"
"		[66]: bool   useOriginalCommand = false;\n"
"		[67]: string originalCommand;\n"
"\n"
"		[71]: int    condition_data_num = 0;\n"
"		[72]: binary condition_data;\n"
"		[73]: int    attrib_data_num = 0;\n"
"		[74]: binary attrib_data;\n"
"\n"
"		[80]: binary battleCommand; // std::array<uint32t, 6>\n"
"	};\n"
"	[12]: array2d Skill\n"
"	{\n"
"		[1]: string name;\n"
"		[2]: string comment;\n"
"		[3]: string messageL1;\n"
"		[4]: string messageL2;\n"
"		[7]: int messageFaild;\n"
"		[8]: int type = 0;\n"
"\n"
"		[11]: int using_mp_Amount = 0;\n"
"		[12]: int range = 0;\n"
"		[13]: int switch_id = 1;\n"
"		[14]: int anime_id  = 1;\n"
"		[16]: sound sound;\n"
"		[18]: bool useAtField  = true ;\n"
"		[19]: bool useAtBattle = false;\n"
"\n"
"		[21]: int blowRelate = 0;\n"
"		[22]: int mindRelate = 3;\n"
"		[23]: int effectSpread = 4;\n"
"		[24]: int basicEffect = 0;\n"
"		[25]: int succeedRate = 100;\n"
"\n"
"		[31]: bool decrease_hp_ = false;\n"
"		[32]: bool decrease_mp_ = false;\n"
"		[33]: bool decreaseAttack  = false;\n"
"		[34]: bool decreaseDefence = false;\n"
"		[35]: bool decreaseMind    = false;\n"
"		[36]: bool decreaseSpeed   = false;\n"
"		[37]: bool absorption = false;\n"
"		[38]: bool ignoreDefence = false;\n"
"\n"
"		[41]: int condition_data_num = 0;\n"
"		[42]: binary condition_data; // std::vector< uint8t > (as bool)\n"
"		[43]: int attrib_data_num = 0;\n"
"		[44]: binary attrib_data; // std::vector< uint8t > (as bool)\n"
"		[45]: bool changeAttrib;\n"
"	};\n"
"	[13]: array2d item\n"
"	{\n"
"		[1]: string name;\n"
"		[2]: string comment;\n"
"		[3]: int type  = 0;\n"
"		[5]: int price = 0;\n"
"		[6]: int usable = 1;\n"
"\n"
"		[11]: int attack  = 0;\n"
"		[12]: int defence = 0;\n"
"		[13]: int mind    = 0;\n"
"		[14]: int speed   = 0;\n"
"\n"
"		[15]: int hand = 0;\n"
"		[16]: int using_mp_ = 0;\n"
"		[17]: int hitRate = 0;\n"
"		[18]: int criticalRate = 0;\n"
"\n"
"		[20]: int anime_id = 1;\n"
"\n"
"		[21]: bool firstStrike = false;\n"
"		[22]: bool doubleAttack = false;\n"
"		[23]: bool attackAll = false;\n"
"		[24]: bool ignoreEvasionRate = false;\n"
"		[25]: bool preventCritical = false;\n"
"		[26]: bool increaseEvasionRate = false;\n"
"		[27]: bool halfUsing_mp_ = false;\n"
"		[28]: bool ignoreTerrainDamage = false;\n"
"		[29]: bool fixequipment = false;\n"
"\n"
"		[31]: int range = 0;\n"
"		[32]: int hpAmount = 0;\n"
"		[33]: int hpRate = 0;\n"
"		[34]: int mpAmount = 0;\n"
"		[35]: int mpRate = 0;\n"
"\n"
"		[37]: bool onlyAtField = false;\n"
"		[38]: bool onlyForKnockout = false;\n"
"\n"
"		[41]: int increase_hp_ = 0;\n"
"		[42]: int increase_mp_ = 0;\n"
"		[43]: int increaseAttack  = 0;\n"
"		[44]: int increaseDefence = 0;\n"
"		[45]: int increaseMind    = 0;\n"
"		[46]: int increaseSpeed   = 0;\n"
"\n"
"		[51]: int message_type = 0;\n"
"		[53]: int skill_id = 1;\n"
"		[55]: int switch_id = 1;\n"
"		[57]: bool useAtField  = true ;\n"
"		// [58]: bool\n"
"		[59]: bool useAtBattle = false;\n"
"\n"
"		[61]: int equip_data_num = 0;\n"
"		[62]: binary equip_data; // std::vector< uint8t > (as bool)\n"
"		[63]: int condition_data_num = 0;\n"
"		[64]: binary condition_data; // std::vector< uint8t > (as bool)\n"
"		[65]: int attrib_data_num = 0;\n"
"		[66]: binary attrib_data; // std::vector< uint8t > (as bool)\n"
"		[67]: int conditionRate = 0;\n"
"		[68]: bool conditionFlip = false;\n"
"		[69]: int useAnime_id;\n"
"\n"
"		[71]: bool useSkillAs_item = false;\n"
"		[72]: int job_data_num = 0;\n"
"		[73]: binary job_data;\n"
"	};\n"
"	[14]: array2d Enemy\n"
"	{\n"
"		[1]: string name;\n"
"		[2]: string monster;\n"
"		[3]: int colorTone = 0;\n"
"		[4]: int hp_ = 10;\n"
"		[5]: int mp_ = 10;\n"
"		[6]: int attack  = 10;\n"
"		[7]: int defence = 10;\n"
"		[8]: int mind    = 10;\n"
"		[9]: int speed   = 10;\n"
"		[10]: bool semiTrans = false;\n"
"		[11]: int exp = 0;\n"
"		[12]: int money = 0;\n"
"		[13]: int dropping_item_id = 0;\n"
"		[14]: int itemDropRate = 100;\n"
"\n"
"		[21]: bool critical = false;\n"
"		[22]: int criticalRate = 30;\n"
"\n"
"		[26]: bool increaseMiss = false;\n"
"		[28]: bool inTheAir = false;\n"
"\n"
"		[31]: int condition_data_num = 0;\n"
"		[32]: binary condition_data;\n"
"		[33]: int attrib_data_num = 0;\n"
"		[34]: binary attrib_data;\n"
"\n"
"		[42]: array2d actionPattern\n"
"		{\n"
"			[1]: int action_type;\n"
"			[2]: int basicaction = 1;\n"
"			[3]: int skill_id = 1;\n"
"			[4]: int enemy_id = 1;\n"
"			[5]: int attackTerm = 0;\n"
"			[6]: int A = 0;\n"
"			[7]: int B = 0;\n"
"			[8]: int switch_id = 1;\n"
"			[9]: bool onAfteraction = false;\n"
"			[10]: int onSwitch_id = 1;\n"
"			[11]: bool offAfteraction = false;\n"
"			[12]: int offSwitch_id = 1;\n"
"			[13]: int priority = 50;\n"
"		};\n"
"	};\n"
"	[15]: array2d EnemyGroup\n"
"	{\n"
"		[1]: string name;\n"
"		[2]: array2d EnemyEnum\n"
"		{\n"
"			[1]: int enemy_id = 1;\n"
"			[2]: int x = 0;\n"
"			[3]: int y = 0;\n"
"			[4]: bool liveJoin = false;\n"
"		};\n"
"		[4]: int terrain_data_num;\n"
"		[5]: binary terrain_data;\n"
"\n"
"		[11]: array2d Battle_event\n"
"		{\n"
"			[2]: array1d Term\n"
"			{\n"
"				[1]: int flag = 0;\n"
"/*\n"
"					[bit]\n"
"					[0]: switch1\n"
"					[1]: switch2\n"
"					[2]: variable\n"
"					[3]: turn\n"
"					[4]: consume\n"
"					[5]: enemy_state\n"
"					[6]: char_state\n"
"*/\n"
"				[2]: int switch_id1 = 1;\n"
"\n"
"				[3]: int switch_id2 = 1;\n"
"\n"
"				[4]: int variable_id = 1;\n"
"				[5]: int value = 0;\n"
"\n"
"				[6]: int trunFreq = 0;\n"
"				[7]: int turnOffset = 0;\n"
"\n"
"				[ 8]: int consumeFrom = 0;\n"
"				[ 9]: int consumeTo   = 100;\n"
"\n"
"				[10]: int enemy_id = 0;\n"
"				[11]: int enemy_hp_from = 0;\n"
"				[12]: int enemy_hp_to   = 100;\n"
"\n"
"				[13]: int char_id = 1;\n"
"				[14]: int char_hp_from = 0;\n"
"				[15]: int char_hp_to   = 100;\n"
"			};\n"
"\n"
"			[11]: int eventLength = 0;\n"
"			[12]: event event;\n"
"		};\n"
"	};\n"
"	[16]: array2d Terrain\n"
"	{\n"
"		[1]: string name;\n"
"		[2]: int damage = 0;\n"
"		[3]: int rate = 100;\n"
"		[4]: string backdrop ;\n"
"		[5]: bool boat = false;\n"
"		[6]: bool ship = false;\n"
"		[7]: bool airship = true;\n"
"		[9]: bool airshipLand = true;\n"
"\n"
"		[11]: int charView_type = 0;\n"
"\n"
"		[15]: sound footstep;\n"
"		[16]: bool on_damage_se;\n"
"		[17]: int background_type;\n"
"\n"
"		[21]: string background_a_name;\n"
"		[22]: bool background_a_scrollh;\n"
"		[23]: bool background_a_scrollv;\n"
"		[24]: int background_a_scrollh_speed;\n"
"		[25]: int background_a_scrollv_speed;\n"
"\n"
"		[30]: bool background_b;\n"
"		[31]: string background_b_name;\n"
"		[32]: bool background_b_scrollh;\n"
"		[33]: bool background_b_scrollv;\n"
"		[34]: int background_b_scrollh_speed;\n"
"		[35]: int background_b_scrollv_speed;\n"
"\n"
"		[40]: int special_flags;\n"
"		[41]: int special_back_party;\n"
"		[42]: int special_back_enemies;\n"
"		[43]: int special_lateral_party;\n"
"		[44]: int special_lateral_enemies;\n"
"		[45]: int grid_location;\n"
"		[46]: int grid_a;\n"
"		[47]: int grid_b;\n"
"		[48]: int grid_c;\n"
"	};\n"
"	[17]: array2d Attribute\n"
"	{\n"
"		[1]: string name;\n"
"		[2]: int type = 0;\n"
"\n"
"		[11]: int rateA = 300;\n"
"		[12]: int rateB = 200;\n"
"		[13]: int rateC = 100;\n"
"		[14]: int rateD = 50;\n"
"		[15]: int rateE = 0;\n"
"	};\n"
"	[18]: array2d Condition\n"
"	{\n"
"		[1]: string name ;\n"
"		[2]: int type = 0;\n"
"		[3]: int color = 6;\n"
"		[4]: int priority = 50;\n"
"		[5]: int restrict = 0;\n"
"\n"
"		[11]: int rateA = 100;\n"
"		[12]: int rateB = 80;\n"
"		[13]: int rateC = 60;\n"
"		[14]: int rateD = 30;\n"
"		[15]: int rateE = 0;\n"
"\n"
"		[21]: int cureturn = 0;\n"
"		[22]: int cureRate = 0;\n"
"		[23]: int shockCureRate = 0;\n"
"\n"
"		[31]: bool attack  = false;\n"
"		[32]: bool defence = false;\n"
"		[33]: bool mind    = false;\n"
"		[34]: bool speed   = false;\n"
"		[35]: int hitRate = 100;\n"
"\n"
"		[41]: bool disableBlowSkill = false;\n"
"		[42]: int blowRelate = 0;\n"
"		[43]: bool disableMindSkill = false;\n"
"		[44]: int mindRelate = 0;\n"
"\n"
"		[51]: string message_member ;\n"
"		[52]: string messageEnemy  ;\n"
"		[53]: string messageAlready;\n"
"		[54]: string messageLast   ;\n"
"		[55]: string messageCure   ;\n"
"\n"
"		[61]: int turn_hp_Amount  = 0;\n"
"		[62]: int turn_hp_Rate    = 0;\n"
"		[63]: int field_hp_Step   = 0;\n"
"		[64]: int field_hp_Amount = 0;\n"
"		[65]: int turn_mp_Amount  = 0;\n"
"		[66]: int turn_mp_Rate    = 0;\n"
"		[67]: int field_mp_Step   = 0;\n"
"		[68]: int field_mp_Amount = 0;\n"
"	};\n"
"	[19]: array2d BattleAnime\n"
"	{\n"
"		[1]: string name ;\n"
"		[2]: string battle ;\n"
"		[6]: array2d Effect\n"
"		{\n"
"			[1]: int frame_id = 0;\n"
"			[2]: sound sound;\n"
"			[3]: int range = 0;\n"
"			[4]: int red   = 31;\n"
"			[5]: int green = 31;\n"
"			[6]: int blue  = 31;\n"
"			[7]: int flash = 31;\n"
"		};\n"
"		[9]: int range = 0;\n"
"		[10]: int ybase = 0;\n"
"		[11]: int useGrid = 0;\n"
"		[12]: array2d Frame\n"
"		{\n"
"			[1]: array2d Cell\n"
"			{\n"
"				[1]: bool visible = true;\n"
"				[2]: int battle_pos; // or pattern\n"
"				[3]: int x = 0;\n"
"				[4]: int y = 0;\n"
"				[5]: int magnify = 0;\n"
"				[6]: int red    = 100;\n"
"				[7]: int green  = 100;\n"
"				[8]: int blue   = 100;\n"
"				[9]: int chroma = 100;\n"
"				[10]: int trans = 0;\n"
"			};\n"
"		};\n"
"	};\n"
"	[20]: array2d chip_set\n"
"	{\n"
"		[1]: string name;\n"
"		[2]: string chip_set;\n"
"		[3]: binary terrain_id; // std::vector< uint16t >\n"
"		[4]: binary lower; // std::vector< uint8t >\n"
"		[5]: binary upper; // std::vector< uint8t >\n"
"\n"
"		[11]: int oceanSequence = 0;\n"
"		[12]: int oceanSpeed    = 0;\n"
"	};\n"
"	[21]: array1d Vocabulary\n"
"	{\n"
"		[1]:string battleStart;\n"
"		[2]:string firstStrike;\n"
"		[3]:string escapeSuccess;\n"
"		[4]:string escapeFailure;\n"
"		[5]:string battleWon;\n"
"		[6]:string battleLost;\n"
"		[7]:string gain_exp;\n"
"		[8]:string earnMoneyBegin;\n"
"		[9]:string earnMoneyEnd;\n"
"		[10]:string itemGet;\n"
"		[11]:string normalAttack;\n"
"		[12]:string criticalAttackParty;\n"
"		[13]:string criticalAttackEnemy;\n"
"		[14]:string defended;\n"
"		[15]:string do_nothing;\n"
"		[16]:string chargePower;\n"
"		[17]:string selfDestruct;\n"
"		[18]:string runAway;\n"
"		[19]:string transform;\n"
"		[20]:string   damageToEnemy;\n"
"		[21]:string npDamageToEnemy;\n"
"		[22]:string   damageToParty;\n"
"		[23]:string npDamageToParty;\n"
"		[24]:string skillFailureA;\n"
"		[25]:string skillFailureB;\n"
"		[26]:string skillFailureC;\n"
"		[27]:string physicalAtrackFailure;\n"
"		[28]:string item_use;\n"
"		[29]:string parameterRecovery;\n"
"		[30]:string parameer_up;\n"
"		[31]:string parameerDown;\n"
"		[32]:string partyAbusorbParameter;\n"
"		[33]:string enemyAbusorbParameter;\n"
"		[34]:string attributeGaurd_up;\n"
"		[35]:string attributeGaurdDown;\n"
"		[36]:string level_up;\n"
"		[37]:string skillMastered;\n"
"\n"
"		[41]:string selectActiion; // shop A\n"
"		[42]:string selectActiionSecond;\n"
"		[43]:string buy;\n"
"		[44]:string sell;\n"
"		[45]:string cancel;\n"
"		[46]:string selectBuying_item;\n"
"		[47]:string buying_item_num;\n"
"		[48]:string endBuy;\n"
"		[49]:string selectSelling_item;\n"
"		[50]:string selling_item_num;\n"
"		[51]:string endSell;\n"
"\n"
"		[54]:string v54 ; // shop B\n"
"		[55]:string v55 ;\n"
"		[56]:string v56 ;\n"
"		[57]:string v57 ;\n"
"		[58]:string v58 ;\n"
"		[59]:string v59 ;\n"
"		[60]:string v60 ;\n"
"		[61]:string v61 ;\n"
"		[62]:string v62 ;\n"
"		[63]:string v63 ;\n"
"		[64]:string v64 ;\n"
"\n"
"		[67]:string v67 ; // shop C\n"
"		[68]:string v68 ;\n"
"		[69]:string v69 ;\n"
"		[70]:string v70 ;\n"
"		[71]:string v71 ;\n"
"		[72]:string v72 ;\n"
"		[73]:string v73 ;\n"
"		[74]:string v74 ;\n"
"		[75]:string v75 ;\n"
"		[76]:string v76 ;\n"
"		[77]:string v77 ;\n"
"\n"
"		[80]:string mes0; // hotel A\n"
"		[81]:string mes1;\n"
"		[82]:string mes2;\n"
"		[83]:string hotelYes;\n"
"		[84]:string hotel_no;\n"
"		[85]:string v85 ; // hotel B\n"
"		[86]:string v86 ;\n"
"		[87]:string v87 ;\n"
"		[88]:string v88 ;\n"
"		[89]:string v89 ;\n"
"\n"
"		[92]:string itemOwned_num;\n"
"		[93]:string itemequiped_num;\n"
"\n"
"		[95]:string moneyName;\n"
"\n"
"		[101]:string battle;\n"
"		[102]:string autoaction;\n"
"		[103]:string escape;\n"
"		[104]:string attackCommand;\n"
"		[105]:string defend;\n"
"		[106]:string use_item;\n"
"		[107]:string useSkill;\n"
"		[108]:string equip;\n"
"\n"
"		[110]:string save;\n"
"\n"
"		[112]:string discardCurrent;\n"
"\n"
"		[114]:string newGame;\n"
"		[115]:string continue;\n"
"\n"
"		[117]:string quit;\n"
"\n"
"		[123]:string level;\n"
"		[124]:string hp;\n"
"		[125]:string mp;\n"
"		[126]:string normalCondition;\n"
"		[127]:string expShort;\n"
"		[128]:string levelShort;\n"
"		[129]:string hpShort;\n"
"		[130]:string mpShort;\n"
"		[131]:string usingMp;\n"
"		[132]:string attack;\n"
"		[133]:string defence;\n"
"		[134]:string mind;\n"
"		[135]:string speed;\n"
"		[136]:string weapon;\n"
"		[137]:string shield;\n"
"		[138]:string armor;\n"
"		[139]:string helmet;\n"
"		[140]:string other;\n"
"\n"
"		[146]:string saveSelectMessage;\n"
"		[147]:string loadSelectMessage;\n"
"		[148]:string save_dataPrefix;\n"
"\n"
"		[151]:string remindDiscarding;\n"
"		[152]:string yes;\n"
"		[153]:string no ;\n"
"	};\n"
"	[22]: array1d System\n"
"	{\n"
"		[10]: int version = 2000;\n"
"\n"
"		[11]: string boat;\n"
"		[12]: string ship;\n"
"		[13]: string airship;\n"
"		[14]: int boat_pos;\n"
"		[15]: int ship_pos;\n"
"		[16]: int airship_pos;\n"
"		[17]: string title;\n"
"		[18]: string gameOver;\n"
"		[19]: string system;\n"
"		[20]: string system2;\n"
"\n"
"		[21]: int member_num = 0;\n"
"		[22]: binary member;\n"
"\n"
"		[26]: int menuCommandSize;\n"
"		[27]: binary menuCommand;\n"
"\n"
"		[31]: music titeBGM;\n"
"		[32]: music battleBGM;\n"
"		[33]: music battleEndBGM;\n"
"		[34]: music innBGM;\n"
"		[35]: music boatBGM;\n"
"		[36]: music shipBGM;\n"
"		[37]: music airshipBGM;\n"
"		[38]: music gameOverBGM;\n"
"\n"
"		[41]: sound cursormoveSE;\n"
"		[42]: sound enterSE;\n"
"		[43]: sound cancelSE;\n"
"		[44]: sound buzzerSE;\n"
"		[45]: sound battleStartSE;\n"
"		[46]: sound escapeSE;\n"
"		[47]: sound enemyAttackSE;\n"
"		[48]: sound enemyDamagedSE;\n"
"		[49]: sound memberDamagedSE;\n"
"		[50]: sound evasionSE;\n"
"		[51]: sound enemyDefeatSE;\n"
"		[52]: sound use_itemSE;\n"
"\n"
"		[61]: int moveErace = 0;\n"
"		[62]: int moveDisplay = 0;\n"
"		[63]: int battleStartErace = 0;\n"
"		[64]: int battleStartDisplay = 0;\n"
"		[65]: int battleEndErace = 0;\n"
"		[66]: int battleEndDisplay = 0;\n"
"\n"
"		[71]: int wallpaper = 0;\n"
"		[72]: int font = 0;\n"
"\n"
"		[81]: int dummy;\n"
"		[82]: bool dummy;\n"
"		[83]: int dummy;\n"
"		[84]: string defBackdrop;\n"
"		[85]: array2d dummy\n"
"		{\n"
"/*\n"
"			[1]: int dummy;\n"
"			[2]: int dummy;\n"
"\n"
"			[11]: int dummy;\n"
"			[12]: int dummy;\n"
"			[13]: int dummy;\n"
"			[14]: int dummy;\n"
"			[15]: int dummy;\n"
"*/\n"
"		};\n"
"\n"
"		[91]: int saveTime;\n"
"	};\n"
"	[23]: array2d Switch\n"
"	{\n"
"		[1]: string name ;\n"
"	};\n"
"	[24]: array2d Variable\n"
"	{\n"
"		[1]: string name ;\n"
"	};\n"
"	[25]: array2d Common_event\n"
"	{\n"
"		[1]: string name ;\n"
"\n"
"		[11]: int start_type = 5;\n"
"		[12]: bool needSwitch = false;\n"
"		[13]: int switch_id = 1;\n"
"\n"
"		[21]: int eventLength;\n"
"		[22]: event event;\n"
"	};\n"
"};\n"
;
} }
